name: Update Tax News

on:
  schedule:
    - cron: '0 * * * *' # 每小時運行一次
  push:
    branches:
      - main

jobs:
  update-news:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install axios cheerio
- name: Fetch tax news
  run: |
    node <<'EOF'
    const axios = require('axios');
    const cheerio = require('cheerio');
    const fs = require('fs');

    const fetchTaxNews = async () => {
        try {
            const response = await axios.get('https://law-out.mof.gov.tw/');
            const html = response.data;
            const $ = cheerio.load(html);

            const taxNews = [];

            // 調整選擇器以符合目標網站的 HTML 結構
            $('.news-item').each((index, element) => {
                const title = $(element).find('.news-title').text().trim();
                const description = $(element).find('.news-description').text().trim();
                const url = $(element).find('a').attr('href');

                taxNews.push({ title, description, url });
            });

            fs.writeFileSync('tax-news.json', JSON.stringify(taxNews, null, 2));
        } catch (error) {
            console.error('Error fetching tax news:', error);
            process.exit(1);
        }
    };

    fetchTaxNews();
    EOF


    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add tax-news.json
        git commit -m "Update tax news"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
